// Signal OS — Rich Demo Dataset
// 20+ posts, 10+ creators, 15+ hashtags, 8 topics

import type { Post, Creator } from './store';

export const mockPosts: Post[] = [
  {
    id: 'p1',
    content: 'Just shipped a new feature that uses AI to predict which of your drafts will perform best. The accuracy is mind-blowing. Thread on how we built it',
    author: 'Alex Chen',
    handle: '@alexchen',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=alex',
    likes: 3420,
    replies: 287,
    reposts: 891,
    impressions: 125000,
    engagement: 4.2,
    sentiment: 'positive',
    score: 87,
    topics: ['AI & Machine Learning', 'Startup & Business'],
    hashtags: ['#AI', '#Startup', '#BuildInPublic'],
    createdAt: '2024-01-15T09:30:00Z',
  },
  {
    id: 'p2',
    content: 'The biggest mistake I see founders make: building for months without talking to users. Ship ugly. Ship fast. Ship often. Your users will tell you what to polish.',
    author: 'Sarah Kim',
    handle: '@sarahkim',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=sarah',
    likes: 5620,
    replies: 412,
    reposts: 1230,
    impressions: 210000,
    engagement: 5.1,
    sentiment: 'positive',
    score: 92,
    topics: ['Startup & Business'],
    hashtags: ['#FounderAdvice', '#StartupLife'],
    createdAt: '2024-01-14T14:15:00Z',
  },
  {
    id: 'p3',
    content: 'Crypto is not dead. It is just getting started. The builders who stayed during the bear market are about to reap the rewards. This cycle will be different.',
    author: 'Marcus Wright',
    handle: '@marcusw',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=marcus',
    likes: 2890,
    replies: 567,
    reposts: 720,
    impressions: 98000,
    engagement: 6.8,
    sentiment: 'positive',
    score: 78,
    topics: ['Crypto & Web3'],
    hashtags: ['#Crypto', '#Web3', '#Bitcoin'],
    createdAt: '2024-01-13T11:00:00Z',
  },
  {
    id: 'p4',
    content: '5 UX patterns every product designer should know:\n\n1. Progressive disclosure\n2. Fitts Law\n3. Hick\'s Law\n4. Gestalt principles\n5. Mental models\n\nWhich one do you use most?',
    author: 'Emma Liu',
    handle: '@emmaliu',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=emma',
    likes: 4150,
    replies: 892,
    reposts: 1560,
    impressions: 178000,
    engagement: 5.6,
    sentiment: 'positive',
    score: 85,
    topics: ['Product & Design'],
    hashtags: ['#UXDesign', '#ProductDesign'],
    createdAt: '2024-01-12T16:45:00Z',
  },
  {
    id: 'p5',
    content: 'Rust is the future of systems programming. Fight me.\n\nAfter 3 years of building in Rust, I can never go back to C++. The safety guarantees alone are worth the learning curve.',
    author: 'David Park',
    handle: '@davidpark',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=david',
    likes: 6780,
    replies: 1234,
    reposts: 890,
    impressions: 245000,
    engagement: 7.2,
    sentiment: 'mixed',
    score: 82,
    topics: ['Engineering & Dev'],
    hashtags: ['#Rust', '#Programming', '#Systems'],
    createdAt: '2024-01-11T08:20:00Z',
  },
  {
    id: 'p6',
    content: 'Growth hack of the week: We added a simple referral prompt after users completed their first milestone. Referrals increased 340%.\n\nSometimes the simplest changes have the biggest impact.',
    author: 'Nina Patel',
    handle: '@ninapatel',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=nina',
    likes: 5230,
    replies: 345,
    reposts: 1890,
    impressions: 198000,
    engagement: 5.8,
    sentiment: 'positive',
    score: 88,
    topics: ['Marketing & Growth', 'Startup & Business'],
    hashtags: ['#GrowthHacking', '#Marketing'],
    createdAt: '2024-01-10T13:30:00Z',
  },
  {
    id: 'p7',
    content: 'The creator economy is oversaturated. But authentic creators will always win. Stop chasing trends. Start chasing truth. Your unique perspective is your moat.',
    author: 'Jordan Blake',
    handle: '@jordanblake',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=jordan',
    likes: 8910,
    replies: 678,
    reposts: 2340,
    impressions: 310000,
    engagement: 6.1,
    sentiment: 'positive',
    score: 91,
    topics: ['Creator Economy'],
    hashtags: ['#CreatorEconomy', '#ContentCreator'],
    createdAt: '2024-01-09T10:15:00Z',
  },
  {
    id: 'p8',
    content: 'Breaking: Google announces new AI model with 10M context window. This changes everything for enterprise applications.\n\nAnalysis of what this means for builders',
    author: 'Tech Insider',
    handle: '@techinsider',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=tech',
    likes: 12400,
    replies: 1560,
    reposts: 4560,
    impressions: 520000,
    engagement: 4.8,
    sentiment: 'positive',
    score: 79,
    topics: ['Tech Industry', 'AI & Machine Learning'],
    hashtags: ['#Google', '#AI', '#TechNews'],
    createdAt: '2024-01-08T18:00:00Z',
  },
  {
    id: 'p9',
    content: 'New study shows that remote workers are 13% more productive than office workers. But the real insight: it depends entirely on the person and the role.\n\nOne size does not fit all.',
    author: 'Lisa Wong',
    handle: '@lisawong',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=lisa',
    likes: 3780,
    replies: 890,
    reposts: 1230,
    impressions: 145000,
    engagement: 5.4,
    sentiment: 'mixed',
    score: 83,
    topics: ['Tech Industry'],
    hashtags: ['#RemoteWork', '#Productivity'],
    createdAt: '2024-01-07T09:45:00Z',
  },
  {
    id: 'p10',
    content: 'I spent $50K on ads last month. Here is exactly what worked and what flopped:\n\n1. Twitter/X ads: 3.2x ROAS\n2. LinkedIn: 1.8x ROAS\n3. Newsletter sponsorships: 4.1x ROAS\n4. Influencer partnerships: 2.5x ROAS\n\nThe lesson? Double down on what works. Cut the rest.',
    author: 'Ryan Torres',
    handle: '@ryantorres',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=ryan',
    likes: 7230,
    replies: 1023,
    reposts: 3450,
    impressions: 280000,
    engagement: 6.2,
    sentiment: 'positive',
    score: 90,
    topics: ['Marketing & Growth'],
    hashtags: ['#Marketing', '#ROAS', '#PaidAds'],
    createdAt: '2024-01-06T15:20:00Z',
  },
  {
    id: 'p11',
    content: 'Your first 1000 followers are the hardest. After that, compound growth kicks in. Focus on consistency over virality. Show up every day.',
    author: 'Mia Johnson',
    handle: '@miajohnson',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=mia',
    likes: 4560,
    replies: 567,
    reposts: 1890,
    impressions: 167000,
    engagement: 5.5,
    sentiment: 'positive',
    score: 86,
    topics: ['Creator Economy'],
    hashtags: ['#Growth', '#Followers', '#Consistency'],
    createdAt: '2024-01-05T11:30:00Z',
  },
  {
    id: 'p12',
    content: 'The best product managers I know all share one trait: they write exceptionally well. Clear writing = clear thinking = better product decisions.\n\nInvest in your writing skills.',
    author: 'Chris Adams',
    handle: '@chrisadams',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=chris',
    likes: 6780,
    replies: 445,
    reposts: 2340,
    impressions: 234000,
    engagement: 5.8,
    sentiment: 'positive',
    score: 89,
    topics: ['Product & Design', 'Startup & Business'],
    hashtags: ['#ProductManagement', '#Writing'],
    createdAt: '2024-01-04T14:00:00Z',
  },
  {
    id: 'p13',
    content: 'Why I switched from React to Svelte for my side projects:\n\n- Less boilerplate\n- Better performance\n- Smaller bundles\n- Truly reactive\n\nNot saying React is bad. But Svelte fits my brain better.',
    author: 'Tom Fischer',
    handle: '@tomfischer',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=tom',
    likes: 2340,
    replies: 890,
    reposts: 567,
    impressions: 98000,
    engagement: 6.0,
    sentiment: 'positive',
    score: 80,
    topics: ['Engineering & Dev'],
    hashtags: ['#Svelte', '#React', '#WebDev'],
    createdAt: '2024-01-03T10:00:00Z',
  },
  {
    id: 'p14',
    content: 'Burnout is not a badge of honor. It is a sign of poor boundaries.\n\nThe most successful people I know work hard but rest harder. Protect your energy.',
    author: 'Anna Silva',
    handle: '@annasilva',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=anna',
    likes: 12340,
    replies: 1230,
    reposts: 4560,
    impressions: 420000,
    engagement: 6.3,
    sentiment: 'positive',
    score: 93,
    topics: ['Health & Wellness'],
    hashtags: ['#Burnout', '#MentalHealth', '#WorkLifeBalance'],
    createdAt: '2024-01-02T16:30:00Z',
  },
  {
    id: 'p15',
    content: 'People do not buy products. They buy better versions of themselves.\n\nFrame your messaging around transformation, not features. That is the difference between good and great marketing.',
    author: 'Ben Harper',
    handle: '@benharper',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=ben',
    likes: 8910,
    replies: 678,
    reposts: 3450,
    impressions: 298000,
    engagement: 5.9,
    sentiment: 'positive',
    score: 91,
    topics: ['Marketing & Growth'],
    hashtags: ['#Marketing', '#Copywriting', '#Positioning'],
    createdAt: '2024-01-01T12:00:00Z',
  },
  {
    id: 'p16',
    content: 'The era of 10x engineers is over. The era of 10x teams is here.\n\nCollaboration, documentation, and knowledge sharing beat individual brilliance every time.',
    author: 'Rachel Green',
    handle: '@rachelgreen',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=rachel',
    likes: 5670,
    replies: 1230,
    reposts: 1890,
    impressions: 198000,
    engagement: 6.5,
    sentiment: 'positive',
    score: 87,
    topics: ['Engineering & Dev', 'Startup & Business'],
    hashtags: ['#Engineering', '#TeamWork', '#Culture'],
    createdAt: '2023-12-31T14:00:00Z',
  },
  {
    id: 'p17',
    content: 'Just published our annual State of AI report. 200+ pages of research on where AI is heading.\n\nKey finding: Multimodal models will be the default by end of 2024.\n\nLink in thread',
    author: 'AI Research Lab',
    handle: '@airesearch',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=ai',
    likes: 4560,
    replies: 345,
    reposts: 2340,
    impressions: 187000,
    engagement: 4.5,
    sentiment: 'positive',
    score: 84,
    topics: ['AI & Machine Learning', 'Science & Research'],
    hashtags: ['#AI', '#Research', '#Report'],
    createdAt: '2023-12-30T10:00:00Z',
  },
  {
    id: 'p18',
    content: 'If you are building a SaaS and not tracking LTV:CAC ratio, you are flying blind.\n\nHealthy ratio: 3:1 or higher\nConcerning: Below 2:1\nCritical: Below 1:1\n\nWhat is your ratio?',
    author: 'Victor Lee',
    handle: '@victorlee',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=victor',
    likes: 3450,
    replies: 1234,
    reposts: 1560,
    impressions: 156000,
    engagement: 6.0,
    sentiment: 'positive',
    score: 85,
    topics: ['Startup & Business'],
    hashtags: ['#SaaS', '#Metrics', '#LTV'],
    createdAt: '2023-12-29T15:30:00Z',
  },
  {
    id: 'p19',
    content: 'Design tip: White space is not empty space. It is active design.\n\nThe best interfaces feel calm because every element has room to breathe. Less is more. Always.',
    author: 'Sophie Martin',
    handle: '@sophiemartin',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=sophie',
    likes: 7890,
    replies: 456,
    reposts: 3450,
    impressions: 267000,
    engagement: 5.2,
    sentiment: 'positive',
    score: 88,
    topics: ['Product & Design'],
    hashtags: ['#Design', '#UX', '#Minimalism'],
    createdAt: '2023-12-28T11:00:00Z',
  },
  {
    id: 'p20',
    content: 'The most underrated skill in tech: reading documentation.\n\n90% of problems can be solved by reading the docs for 10 minutes. But most people would rather spend hours debugging.',
    author: 'Kevin Zhang',
    handle: '@kevinzhang',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=kevin',
    likes: 10230,
    replies: 890,
    reposts: 4560,
    impressions: 345000,
    engagement: 5.4,
    sentiment: 'positive',
    score: 90,
    topics: ['Engineering & Dev'],
    hashtags: ['#Programming', '#DevTips', '#Documentation'],
    createdAt: '2023-12-27T13:00:00Z',
  },
  {
    id: 'p21',
    content: 'Content creation is not about being the smartest person in the room. It is about being the most helpful.\n\nShare what you learned yesterday. Someone is struggling with that today.',
    author: 'Laura Adams',
    handle: '@lauraadams',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=laura',
    likes: 6780,
    replies: 567,
    reposts: 2340,
    impressions: 234000,
    engagement: 5.6,
    sentiment: 'positive',
    score: 92,
    topics: ['Creator Economy'],
    hashtags: ['#ContentCreation', '#Helpful', '#Community'],
    createdAt: '2023-12-26T10:30:00Z',
  },
  {
    id: 'p22',
    content: 'AI will not replace you. But someone using AI will.\n\nThe winners of the next decade will be those who learn to work WITH AI, not against it.\n\nStart experimenting today.',
    author: 'Mark Stevens',
    handle: '@markstevens',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=mark',
    likes: 15670,
    replies: 2340,
    reposts: 6780,
    impressions: 560000,
    engagement: 7.8,
    sentiment: 'positive',
    score: 94,
    topics: ['AI & Machine Learning'],
    hashtags: ['#AI', '#FutureOfWork', '#Productivity'],
    createdAt: '2023-12-25T09:00:00Z',
  },
];

export const mockCreators: Creator[] = [
  {
    id: 'c1', name: 'Alex Chen', handle: '@alexchen',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=alex',
    bio: 'Building AI tools for creators. Previously @Google. Writing about tech, startups, and the future of work.',
    followers: 45200, following: 890, posts: 1230, engagement: 4.8,
    qualityScore: 88, niche: 'AI & Startups', verified: true,
  },
  {
    id: 'c2', name: 'Sarah Kim', handle: '@sarahkim',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=sarah',
    bio: '2x founder. 1 exit. Sharing unfiltered startup lessons. Advisor to early-stage founders.',
    followers: 89100, following: 1200, posts: 2340, engagement: 5.2,
    qualityScore: 92, niche: 'Startups', verified: true,
  },
  {
    id: 'c3', name: 'Marcus Wright', handle: '@marcusw',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=marcus',
    bio: 'Crypto researcher and analyst. Building in Web3 since 2017. Not financial advice.',
    followers: 23400, following: 450, posts: 5670, engagement: 6.1,
    qualityScore: 76, niche: 'Crypto & Web3', verified: false,
  },
  {
    id: 'c4', name: 'Emma Liu', handle: '@emmaliu',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=emma',
    bio: 'Product Designer @Figma. Teaching UX/UI through threads and case studies.',
    followers: 67800, following: 890, posts: 1890, engagement: 5.5,
    qualityScore: 90, niche: 'Design', verified: true,
  },
  {
    id: 'c5', name: 'David Park', handle: '@davidpark',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=david',
    bio: 'Systems engineer. Rust evangelist. Open source contributor. Writing about software architecture.',
    followers: 34500, following: 670, posts: 890, engagement: 4.9,
    qualityScore: 85, niche: 'Engineering', verified: false,
  },
  {
    id: 'c6', name: 'Nina Patel', handle: '@ninapatel',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=nina',
    bio: 'Growth Lead @Stripe. Sharing growth experiments and marketing frameworks that actually work.',
    followers: 56700, following: 1200, posts: 1560, engagement: 5.3,
    qualityScore: 89, niche: 'Growth Marketing', verified: true,
  },
  {
    id: 'c7', name: 'Jordan Blake', handle: '@jordanblake',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=jordan',
    bio: 'Creator economy researcher. Helping creators build sustainable businesses. Host of The Creator Podcast.',
    followers: 123000, following: 890, posts: 2340, engagement: 5.8,
    qualityScore: 91, niche: 'Creator Economy', verified: true,
  },
  {
    id: 'c8', name: 'Anna Silva', handle: '@annasilva',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=anna',
    bio: 'Mental health advocate for tech workers. Burnout survivor. Writing about sustainable high performance.',
    followers: 78900, following: 670, posts: 1230, engagement: 6.2,
    qualityScore: 93, niche: 'Wellness', verified: true,
  },
  {
    id: 'c9', name: 'Chris Adams', handle: '@chrisadams',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=chris',
    bio: 'Product Manager @Notion. Writing about product strategy, decision-making, and team building.',
    followers: 45600, following: 890, posts: 1670, engagement: 5.0,
    qualityScore: 87, niche: 'Product', verified: true,
  },
  {
    id: 'c10', name: 'Ryan Torres', handle: '@ryantorres',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=ryan',
    bio: 'Performance marketer. $10M+ spent on ads. Sharing real numbers and strategies that scale.',
    followers: 23400, following: 450, posts: 890, engagement: 6.0,
    qualityScore: 84, niche: 'Marketing', verified: false,
  },
  {
    id: 'c11', name: 'Laura Adams', handle: '@lauraadams',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=laura',
    bio: 'Content strategist. Helping founders and creators find their voice. Newsletter: 50K+ subscribers.',
    followers: 34500, following: 670, posts: 1230, engagement: 5.4,
    qualityScore: 90, niche: 'Content Strategy', verified: true,
  },
];

export const mockHashtags = [
  { tag: '#AI', posts: 45200, engagement: 5.2, trending: true, velocity: 78 },
  { tag: '#Startup', posts: 23400, engagement: 4.8, trending: true, velocity: 65 },
  { tag: '#Crypto', posts: 67800, engagement: 6.1, trending: false, velocity: 32 },
  { tag: '#UXDesign', posts: 12300, engagement: 4.5, trending: true, velocity: 54 },
  { tag: '#Programming', posts: 89100, engagement: 4.9, trending: true, velocity: 71 },
  { tag: '#Marketing', posts: 34500, engagement: 5.1, trending: false, velocity: 45 },
  { tag: '#CreatorEconomy', posts: 8900, engagement: 5.8, trending: true, velocity: 82 },
  { tag: '#RemoteWork', posts: 56700, engagement: 4.2, trending: false, velocity: 28 },
  { tag: '#Rust', posts: 12300, engagement: 6.5, trending: true, velocity: 73 },
  { tag: '#ProductManagement', posts: 23400, engagement: 4.6, trending: false, velocity: 41 },
  { tag: '#MentalHealth', posts: 78900, engagement: 5.3, trending: true, velocity: 69 },
  { tag: '#SaaS', posts: 45600, engagement: 4.7, trending: true, velocity: 58 },
  { tag: '#Web3', posts: 34500, engagement: 5.9, trending: false, velocity: 35 },
  { tag: '#GrowthHacking', posts: 12300, engagement: 5.5, trending: true, velocity: 76 },
  { tag: '#ContentCreation', posts: 56700, engagement: 5.0, trending: true, velocity: 63 },
  { tag: '#TechNews', posts: 23400, engagement: 4.3, trending: false, velocity: 48 },
  { tag: '#Design', posts: 67800, engagement: 4.4, trending: true, velocity: 55 },
  { tag: '#FutureOfWork', posts: 34500, engagement: 4.8, trending: true, velocity: 67 },
];

export const mockTopics = [
  { name: 'AI & Machine Learning', posts: 1240, engagement: 5.2, sentiment: 72, trend: 'up', related: ['GPT-4', 'LLMs', 'Generative AI', 'AI Agents'] },
  { name: 'Startup & Business', posts: 980, engagement: 4.9, sentiment: 68, trend: 'up', related: ['Fundraising', 'Product-Market Fit', 'Growth', 'Hiring'] },
  { name: 'Engineering & Dev', posts: 1560, engagement: 5.1, sentiment: 65, trend: 'stable', related: ['Rust', 'TypeScript', 'System Design', 'Open Source'] },
  { name: 'Product & Design', posts: 720, engagement: 4.7, sentiment: 70, trend: 'up', related: ['UX Research', 'Design Systems', 'Figma', 'Accessibility'] },
  { name: 'Creator Economy', posts: 890, engagement: 5.8, sentiment: 75, trend: 'up', related: ['Monetization', 'Newsletters', 'Personal Brand', 'Community'] },
  { name: 'Crypto & Web3', posts: 650, engagement: 6.2, sentiment: 45, trend: 'down', related: ['DeFi', 'NFTs', 'Layer 2', 'DAOs'] },
  { name: 'Marketing & Growth', posts: 780, engagement: 5.0, sentiment: 62, trend: 'stable', related: ['SEO', 'Paid Ads', 'Content Marketing', 'Analytics'] },
  { name: 'Health & Wellness', posts: 540, engagement: 5.4, sentiment: 78, trend: 'up', related: ['Mental Health', 'Productivity', 'Burnout', 'Work-Life Balance'] },
];

// KPI data for dashboard
export const kpiData = {
  totalPosts: 2847,
  totalImpressions: 4520000,
  avgEngagement: 5.4,
  avgScore: 84,
  followersGained: 2340,
  bestPerformingDay: 'Tuesday',
  topTopic: 'AI & Machine Learning',
  draftsAnalyzed: 156,
};

// Sparkline data (7-day)
export const sparklineData = {
  impressions: [45, 52, 48, 61, 58, 72, 68],
  engagement: [3.8, 4.2, 4.5, 5.1, 4.8, 5.6, 5.4],
  followers: [120, 180, 150, 220, 190, 310, 280],
  score: [78, 80, 82, 81, 85, 84, 86],
};

// Timeline events
export const timelineEvents = [
  { id: 'e1', date: '2024-01-15', time: '09:30', type: 'post', title: 'AI Feature Launch Thread', impact: 'high', description: 'Announced new AI prediction feature' },
  { id: 'e2', date: '2024-01-15', time: '11:00', type: 'engagement', title: 'Viral Reply', impact: 'medium', description: 'Reply to @sarahkim got 500+ likes' },
  { id: 'e3', date: '2024-01-14', time: '14:15', type: 'milestone', title: '200K Impressions', impact: 'high', description: 'Daily impressions crossed 200K for first time' },
  { id: 'e4', date: '2024-01-14', time: '16:30', type: 'trend', title: '#BuildInPublic Trending', impact: 'medium', description: 'Hashtag entered trending topics' },
  { id: 'e5', date: '2024-01-13', time: '10:00', type: 'post', title: 'Weekly Newsletter', impact: 'low', description: 'Published weekly insights newsletter' },
  { id: 'e6', date: '2024-01-13', time: '18:00', type: 'engagement', title: 'AMA Session', impact: 'high', description: 'Hosted live AMA, 200+ questions answered' },
  { id: 'e7', date: '2024-01-12', time: '09:00', type: 'milestone', title: '50K Followers', impact: 'high', description: 'Reached 50,000 follower milestone' },
  { id: 'e8', date: '2024-01-12', time: '15:30', type: 'trend', title: 'AI Topic Surge', impact: 'medium', description: 'AI-related content saw 40% engagement boost' },
];

// Weekly report data
export const weeklyReportData = {
  period: 'Jan 9 - Jan 15, 2024',
  posts: 12,
  impressions: 156000,
  engagement: 5.4,
  newFollowers: 2340,
  profileVisits: 8900,
  mentions: 456,
  topPost: mockPosts[0],
  bestDay: 'Tuesday',
  growth: { impressions: 12.5, engagement: 8.3, followers: 23.4 },
};

// Score history
export const scoreHistory = [
  { date: '2024-01-15', score: 87 },
  { date: '2024-01-14', score: 92 },
  { date: '2024-01-13', score: 78 },
  { date: '2024-01-12', score: 85 },
  { date: '2024-01-11', score: 82 },
  { date: '2024-01-10', score: 88 },
  { date: '2024-01-09', score: 91 },
  { date: '2024-01-08', score: 79 },
  { date: '2024-01-07', score: 83 },
  { date: '2024-01-06', score: 90 },
];

// Sentiment timeline
export const sentimentTimeline = [
  { date: '2024-01-15', positive: 72, negative: 15, neutral: 13 },
  { date: '2024-01-14', positive: 68, negative: 18, neutral: 14 },
  { date: '2024-01-13', positive: 55, negative: 25, neutral: 20 },
  { date: '2024-01-12', positive: 70, negative: 16, neutral: 14 },
  { date: '2024-01-11', positive: 65, negative: 20, neutral: 15 },
  { date: '2024-01-10', positive: 74, negative: 14, neutral: 12 },
  { date: '2024-01-09', positive: 71, negative: 16, neutral: 13 },
];

// Forecast data
export const forecastData = {
  nextWeek: { bull: 185000, base: 156000, bear: 98000 },
  nextMonth: { bull: 820000, base: 680000, bear: 420000 },
  confidence: 72,
  factors: ['Consistent posting schedule', 'AI topic momentum', 'Growing follower base'],
};

// Command center metrics
export const commandMetrics = {
  firstHour: {
    impressions: 2340,
    engagement: 8.2,
    replies: 45,
    reposts: 67,
    likes: 890,
    profileClicks: 123,
    linkClicks: 89,
  },
  benchmarks: {
    impressions: { you: 2340, avg: 1200, top10: 5600 },
    engagement: { you: 8.2, avg: 3.4, top10: 12.1 },
    replies: { you: 45, avg: 12, top10: 89 },
  },
};

// Settings
export const defaultSettings = {
  theme: 'dark' as const,
  fontSize: 'medium' as const,
  compactMode: false,
  animations: true,
  soundEffects: false,
  autoSave: true,
  scoringWeights: {
    hook: 1.0,
    readability: 1.0,
    engagement: 1.0,
    sentiment: 1.0,
    structure: 1.0,
  },
  notifications: {
    email: true,
    browser: true,
    weekly: true,
    mentions: true,
  },
  connectedAccounts: {
    twitter: true,
    linkedin: false,
    threads: false,
  },
};

export default {
  mockPosts,
  mockCreators,
  mockHashtags,
  mockTopics,
  kpiData,
  sparklineData,
  timelineEvents,
  weeklyReportData,
  scoreHistory,
  sentimentTimeline,
  forecastData,
  commandMetrics,
  defaultSettings,
};
